version: 2

jobs:
  build:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: Install OpenTURNS
          command: |
            sudo pip3 install numpy
            sudo pip3 install scipy
            sudo pip3 install matplotlib
            sudo pip3 install jupyter
            sudo pip3 install openturns
      - run:
          name: Test script
          command: |
            python test.py

